### ISSUE TITLE
v3.9.0.1 throws an error on Moodle 3.7.6

### ISSUE THREAD

**Issue by bret-miller** [roelmann/moodle-block_course_contacts#26]
The is_guest() call is throwing an error on Moodle 3.7.6. Apparently it can't get a course context so it just throws an error. I had to comment the line out and replace it with $isguest=false; to get past it. Maybe a try/catch block or check the Moodle version before calling it?

**Comment by roelmann** [comment]
That's very strange as I have it running on Moodle3.7.3, 3.8 and 3.9DEV with no errors

Can you give me the exact steps to replicate please - who you are logged in as, on what page you have the block, etc.

**Comment by bret-miller** [comment]
I updated to Moodle 3.7.6+ today. Also had 3.7.5+ on another site. On both sites, updating the plugin to 3.9.0.1 caused it to throw an exception as soon as the plugin update was complete. So maybe it's a compatibility issue with the latest Moodle update.

**Comment by roelmann** [comment]
Moodle 3.7.6+ (Build: 20200512) to test, pulled STABLE_39 branch from git.
No errors on a fresh install.
I'll try tomorrow installing an old version and upgrading and see if that causes the error you're seeing...

**Comment by bret-miller** [comment]
![error](https://user-images.githubusercontent.com/12238647/81727369-de8b7080-9456-11ea-911c-432e5ddfafe3.jpg)

There's a screen shot of the error in case it helps.

**Comment by roelmann** [comment]
Ah - from the end of that screenshot, you have the block on the my/index.php page?
`line 164 of /my/index.php: call to coure_renderer->header()`
Then it won't give a course context, because that's not a course.
But the block should not be able to be added to the My index page anyway... It isn't on my test sites
![image](https://user-images.githubusercontent.com/1045679/81729130-638c7f00-9483-11ea-85bc-c6830f9ffd02.png)

**Comment by roelmann** [comment]
OK. If I add it to the front page and say to add it to every course page, I get the error.
Right, I'll add a fix to ensure it is not displayed on the dashboard page - or only on a course page.

Thank you.

**Comment by bret-miller** [comment]
Thank you. You're awesome.

**Comment by roelmann** [comment]
Hmm, 'my' is already set to false - which is why you can't add the block to a dashboard page already. OK, will think of something to strengthen that when it's set as a sticky block...

**Comment by roelmann** [comment]
OK, the fix is this Bret - so that the block will only appear where it is intended to, on course pages (Site Home page is a special type of course page, so it should also appear there so can still be added as a sticky block)

        $courseid = $this->page->course->id;
        $context = $this->page->context;
        **if($context->contextlevel != 50) {
            return;
        }**
        $isguest = is_guest($context);

I'll add this up to my master branch on git tomorrow and push a fix to the plugins database
