### ISSUE TITLE
Users with multiple role assignments

### ISSUE THREAD

**Issue by mkpelletier** [roelmann/moodle-block_course_contacts#3]
Users with multiple role assignments are listed multiple times if more than one of his/her roles are selected in the block configuration.  It would be useful to prioritise roles, selecting only those which are higher in the role hierarchy.

**Comment by roelmann** [comment]
What role hierarchy?
I am not aware of a hierarchy of roles in Moodle. Are you suggesting using the role ID order? Or the order displayed on the Roles screen?

**Comment by mkpelletier** [comment]
There is a role hierarchy in Moodle.  It is assumed for role-stacking purposes.  This is defined in mdl_role.sortorder.  The lower the number, the higher it sits in the hierarchy.  This is used by the renderer to sort the roles on the define roles screen.

**Comment by roelmann** [comment]
I've never regarded the display/sort order as being a hierarchy, although it could be used as such. Its simply an order to display them in. 
For example, in one installation I have roles for both Library staff and HelpDesk staff. HelpDesk sits higher in my roles list because I currently organise it alphabetically. A user may belong to both and both could be on the roles chosen to be displayed - but knowing that someone is the subject librarian may be more useful to a student than knowing that they are available on the Helpdesk, but if only one role was shown according to the 'hierarchy' then only the Helpdesk role would display.
In other institutions I have used the sort order to group roles by function (all the internal teaching roles together, all the franchise partner/external body teaching roles together, all the support roles together, etc).

A better solution might be to create a display hierarchy within this specific block - 'Allow only single role' then rather than a straight tick box, have a ranking of the selected displayed roles...
Will think about these approaches and best way to achieve this.

**Comment by mkpelletier** [comment]
Thanks Richard.

**Comment by roelmann** [comment]
On dev new version to be released soon
